name: Speaker
form: $/sitesforchurch/sermonmanager/models/speaker/fields.yaml
modelClass: Sitesforchurch\SermonManager\Models\Speaker
defaultRedirect: sitesforchurch/sermonmanager/speakers
create:
    title: 'Create Speaker'
    redirect: 'sitesforchurch/sermonmanager/speakers/update/:id'
    redirectClose: sitesforchurch/sermonmanager/speakers
update:
    title: 'Edit Speaker'
    redirect: sitesforchurch/sermonmanager/speakers
    redirectClose: sitesforchurch/sermonmanager/speakers
preview:
    title: 'Preview Speaker'
