name: Sermon
form: $/sitesforchurch/sermonmanager/models/sermon/fields.yaml
modelClass: Sitesforchurch\SermonManager\Models\Sermon
defaultRedirect: sitesforchurch/sermonmanager/sermons
create:
    title: 'Create Sermon'
    redirect: 'sitesforchurch/sermonmanager/sermons/update/:id'
    redirectClose: sitesforchurch/sermonmanager/sermons
update:
    title: 'Edit Sermon'
    redirect: sitesforchurch/sermonmanager/sermons
    redirectClose: sitesforchurch/sermonmanager/sermons
preview:
    title: 'Preview Sermon'
