title: 'Manage Sermons'
modelClass: SitesForChurch\SermonManager\Models\Sermon
list: $/sitesforchurch/sermonmanager/models/sermon/columns.yaml
recordUrl: 'sitesforchurch/sermonmanager/sermons/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: 1
showSorting: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
