name: Series
form: $/sitesforchurch/sermonmanager/models/series/fields.yaml
modelClass: Sitesforchurch\SermonManager\Models\Series
defaultRedirect: sitesforchurch/sermonmanager/series
create:
    title: 'Create Series'
    redirect: 'sitesforchurch/sermonmanager/series/update/:id'
    redirectClose: sitesforchurch/sermonmanager/series
update:
    title: 'Edit Series'
    redirect: sitesforchurch/sermonmanager/series
    redirectClose: sitesforchurch/sermonmanager/series
preview:
    title: 'Preview Series'
