title: 'Manage Series'
modelClass: SitesForChurch\SermonManager\Models\Series
list: $/sitesforchurch/sermonmanager/models/series/columns.yaml
recordUrl: 'sitesforchurch/sermonmanager/series/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: 1
showSorting: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
